 version: 2

 build:
   os: "ubuntu-24.04"
   tools:
     python: "3"
   # We recommend using a requirements file for reproducible builds.
   # This is just a quick example to get started.
   # https://docs.readthedocs.io/page/guides/reproducible-builds.html
   jobs:
     pre_install:
       - pip install mkdocs-material

# We recommend specifying your dependencies to enable reproducible builds:
# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
    - requirements: requirements.txt


 mkdocs:
   configuration: mkdocs.yml
