site_name: Teaching with TACC
repo_url: https://github.com/TACC/TeachingWithTACC
nav:
    - Home: index.md
    - Getting Set Up:
        - Create a TACC Account: 01.create_account.md
        - Choose the Right Resource: 01.choose_resource.md
        - Request an Allocation: 01.request_allocation.md
        - Manage Student Accounts: 01.manage_accounts.md
        - Install Class Software: 01.install_software.md
    - Running the Class:
        - Share Project Files: 02.sharing_files.md
        - Work Interactively on a Node: 02.work_interactively.md
        - Submit Jobs to the Queue: 02.running_jobs.md
        - Request a Queue Reservation: 02.reservation_requests.md
        - Helpful Commands: 02.helpful_commands.md
    - Using the UTRC Portal:
        - Getting Started: 03.getting_started.md
        - Managing Data: 03.managing_data.md
        - Accessing Data: 03.accessing_data.md
        - Additional Features of the UTRC Portal: 03.add_features.md
theme: readthedocs
