site_name: Teaching with TACC
repo_url: https://github.com/TACC/TeachingWithTACC
nav:
    - Home: index.md
    - Setting Up:
        - Create a TACC Account: 01.create_account.md
        - Choose the Right Resource: 01.choose_resource.md
        - Request an Allocation: 01.request_allocation.md
        - Manage Student Access: 01.manage_access.md
        - Install Class Software: 01.install_software.md
    - Running the Class:
        - Share Project Files: 02.sharing_files.md
        - Work Interactively on a Node: 02.work_interactively.md
        - Submit Jobs to the Queue: 02.running_jobs.md
        - Request a Queue Reservation: 02.reservation_requests.md
        - Helpful Commands: 02.helpful_commands.md
    - Using the UTRC Portal:
        - Get Started: 03.getting_started.md
        - Manage Data: 03.managing_data.md
        - Access Data: 03.accessing_data.md
        - Run Applications: 03.run_applications.md
theme: readthedocs
